[tool.poetry]
name = "option-bot"
version = "0.1.0"
description = ""
authors = ["Jody Hirschi <jhirschibar@gmail.com>"]
readme = "README.md"
packages = [{include = "option_bot"}]

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.28.2"
polygon-api-client = "^1.6.2"
pydantic = "^1.10.4"
mypy = "^0.991"
black = "^22.12.0"
isort = "^5.11.4"
flake8 = "^6.0.0"
types-requests = "^2.28.11.8"
pandas = "^1.5.3"
sqlalchemy = "^2.0.0"
psycopg2-binary = "^2.9.5"
alembic = "^1.9.2"
torch = "^1.13.1"
pyrh = {path = "/home/jhirschi/pyrh"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
